networks:
  datenanalyse_in_unternehmen:
    driver: bridge

services:
  grafana-image-renderer:
    image: grafana/grafana-image-renderer
    container_name: grafana-image-renderer
    ports:
      - "8081:8081"
    restart: always
    networks:
      - datenanalyse_in_unternehmen
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=Maximax123
      - GF_RENDERING_SERVER_URL=http://grafana-image-renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug
      - GF_SERVER_ROOT_URL=http://vps1.billiboisbande.de:3000
      - GF_SERVER_DOMAIN=vps1.billiboisbande.de
    volumes:
      - ./grafana_data:/var/lib/grafana
    networks:
      - datenanalyse_in_unternehmen
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    ports:
      - "5000:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Maximax123
      PGOPTIONS: "-c idle_in_transaction_session_timeout=0 -c statement_timeout=0 -c tcp_keepalives_idle=600 -c tcp_keepalives_interval=60 -c tcp_keepalives_count=10"
    volumes:
      - ./timescaledb-data:/var/lib/postgresql/data
    networks:
      - datenanalyse_in_unternehmen
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=EUROPE/BERLIN
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_USER_FOLDER=/home/node/.n8n
      - N8N_SECURE_COOKIE=false
    volumes:
      - ./n8n-data:/data
      - ./n8n-workflows:/home/node/.n8n
    networks:
      - datenanalyse_in_unternehmen
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=Maximax123
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - datenanalyse_in_unternehmen
