networks:
  datenanalyse_in_unternehmen:
    driver: bridge

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    mem_limit: 8g
    memswap_limit: 10g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Maximax123
    volumes:
      - ./mongodb-data:/data/db
    networks:
      - datenanalyse_in_unternehmen
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=EUROPE/BERLIN
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_USER_FOLDER=/home/node/.n8n
      - N8N_SECURE_COOKIE=false
    volumes:
      - ./n8n-data:/data
      - ./n8n-workflows:/home/node/.n8n
    networks:
      - datenanalyse_in_unternehmen
